spring:
  cache:
    redis:
      time-to-live: 3600
  redis:
    database: 0
    host: redis-data-master.redis.svc.cluster.local
    port: 6379
    timeout: 3600
    password: M8JOzfkeDP
  data:
    elasticsearch:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb+srv://b2cDictionaryReadOnly:8Yeoc9kQZJ0z8J66@atlas1-l1978.mongodb.net/B2cProd?retryWrites=true&w=majority
      database: B2cProd
      auto-index-creation: false
  datasource:
    hikari:
      connection-timeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://lhh.cc1m4ag9m6ii.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: SFRUVzJOZPJPSZti1jJm

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
server:
  forward-headers-strategy: framework
mongodb.uri: mongodb+srv://demoUser:3ePHQtAN66Wg@dev-lhh.l1978.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
mongodb.database: myFirstDatabase
mongodb.auto-index-creation: true
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
springdoc:
  version: v2
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: false

enterprise:
  api:
    url: https://demo-acn.skyhive.io
#server.servlet.context-path= /jobs
logging.level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG
esHost: https://search-dev-lhh-u44us5kpczhyu4xvwsfkwy6ivu.us-east-1.es.amazonaws.com
esPassword: Devlhh@2012
esUsername: dev-lhh