name: 'sast'

on:
  workflow_dispatch

jobs:
  sast:
    name: 'sast process'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Self sast-scan
      run: echo "$VERACODE_API_ID"
