name: 'sast'

on:
  workflow_dispatch

jobs:
  sast:
    name: 'sast process'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Self sast-scan
      uses: AppThreat/sast-scan-action@v1.0.0
      with:
          output: reports
          type: java
    - name: Upload scan reports
      uses: actions/upload-artifact@v1.0.0
      with:
         name: sast-scan-reports
         path: reports
