name: 'Tenable'
on:
 workflow_dispatch

jobs:
  DAST:
    name: 'Container security'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: git repo Checkout
      uses: actions/checkout@v2
    
    - name: Runs the container security scan
      uses: tenable/container-security-action@v1
      id: consec
      with:
         repo_name: 157506822563.dkr.ecr.us-east-2.amazonaws.com/demo
         tag_name: latest
      env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
