name: 'tagging'

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  testing:
    name: 'testing process'
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    defaults:
      run:
        shell: bash

    steps:
    - name: git repo Checkout
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'		
        cache: maven
