name: 'tagging'

on:
  push:
    branches:
    - stable
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  testing:
    name: 'testing process'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: check tag
      id: check-tag
      run : | 
       if [[ ${{ github.event.ref }} =~ ^refs/tags/master ]]; then
       echo ""set-output name=match::true
       fi    

    - name: checking the tag status
      if: steps.check-tag.outputs.match == 'true'
      run: |
          echo "Tag is a match"
          
    - name: git repo Checkout
      uses: actions/checkout@v2
      
    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'		
        cache: maven
