name: 'facadapi-1'

on:
  workflow_dispatch

jobs:
  facadapi:
    name: 'facadapi process'
    runs-on: ubuntu-latest
    env:
      ECR_URL:  157506822563.dkr.ecr.us-east-2.amazonaws.com
      AWS_REGION: us-east-2
      EKS_CLUSTERNAME: EKS-cluster
    defaults:
      run:
        shell: bash

    steps:
    - name: git repo Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'		
        cache: maven

    - name: Build the maven
      run:  |
         mvn clean install spring-boot:build-image
         docker images
         
    - name: Zip Project
      run: |
         zip -R project.zip '*.jar'
         ls -al
         pwd
      env:
          build-name: project.zip
