name: 'DAST'

on:
 workflow_dispatch

jobs:
  DAST:
    name: 'DAST process'
    runs-on: test1
    defaults:
      run:
        shell: bash

    steps:
    - name: git repo Checkout
      uses: actions/checkout@v2
    
    - name: setup of go
      uses: actions/setup-go@v2
      with:
          go-version: 1.17
    - name: Nuclei - DAST Scan
      uses: projectdiscovery/nuclei-action@main
      with:
          target: https://www.google.com/

    - name: GitHub Workflow artifacts
      uses: actions/upload-artifact@v2
      with:
          name: nuclei.log
          path: nuclei.log

    - name: GitHub Security Dashboard Alerts update
      uses: github/codeql-action/upload-sarif@v1
      with:
          sarif_file: nuclei.sarif		  
