name: 'DAST'
on:
 workflow_dispatch

jobs:
  DAST:
    name: 'DAST process'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: git repo Checkout
      uses: actions/checkout@v2
    
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.2.0
      with:
         docker_name: 'owasp/zap2docker-stable'
         target: 'https://demo-e.skyhive.io/'
         token: ${{ secrets.GITHUB_TOKEN }}
