name: 'tagging'

on:
  push:
  create:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  testing:
    name: 'testing process'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Check Tag
      run: |
        if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9].[0-9]+.[0-9]+ ]]; then
          echo ::set-output name=match::true
        fi
     
    - name: git repo Checkout
      uses: actions/checkout@v2
      
    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'		
        cache: maven
