name: 'DAST'
on:
 workflow_dispatch

jobs:
  DAST:
    name: 'DAST process'
    runs-on: test1
    defaults:
      run:
        shell: bash

    steps:
    - name: git repo Checkout
      uses: actions/checkout@v2
    
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.3.0
      with:
         docker_name: 'owasp/zap2docker-stable'
         target: 'https://www.google.com/'
         token: ${{ secrets.GITHUB_TOKEN }}

    - name: GitHub Workflow artifacts
      uses: actions/upload-artifact@v2
      with:
          name: ZAP.log
          path: ZAP.log

    - name: GitHub Security Dashboard Alerts update
      uses: github/codeql-action/upload-sarif@v1
      with:
          sarif_file: ZAP.sarif
